config:
  aks:clientId: 83b1af70-aafd-44db-b8a9-0f970c1ee3c2
  aks:clientSecret:
    secure: AAABAPMxe2RLfT8rNCzj2XCjtoCzz96gP2CnkhJcKirw1ByOcW9EJ7LRu7Onbk+KFusczyufR7+Zay5PGoO7q944iV0Pc+WbpxiIkg==
  aks:sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHkRbCVp1wdRZ4GDIBsU1Bmq3j8fucyczlQTJS5Tj5pERIFdihau8bVA7nrjL0cAueoa5B/5XoMeFkpVbEqQVeA5q4c1gCL5PRx4uOPW/HV4bKjh4i6NY+bBThxAmclfSbjvUY53Eb/O45I42JhiA4T3EnOdsF21PFkZ/FBiq5G60RwA3N4s93Jx2QCwYWMg6u1BAVZBWEwe0rKcTpD1rR082Ol3KzrBJL1CtmW/uwIGrbfn7aAtl8k+AU28OFh2/v21VcUEl+PAnWeI5e3w3PH1DCF1CRiXqO6NlHzpIFd8VjiLhIKwV7xcC6U3eveST7Rqa70xxx6eGspLUF/UNv
    benjamin@DESKTOP-6QUE852
